코틀린 첫 과제 제출합니다!
BI-kotlin-in-action/YuChangHo-Project pull request #1
Opened 2023-11-07 14:43 UTC by uch0731

리포지토리 새로 만들고 또 잘 안되길래 서칭좀 하다가 좀 늦었습니다...죄송합니다
코틀린 첫 과제 다시 제출합니다. ㅜㅜ
선택사항에서는 우선 3번 진행했습니다.
3. 각 코드의 역할과 도메인에 따라 파일 혹은 패키지를 분리해본다.

1번과5번도 같이 진행하고 있는데 아직 완료하진 못했습니다ㅜㅜ
1. 모든 validation을 세세하게 지정해본다
5. 수익금이 발생하면 해당 수익금으로 구매 가능한 최대한의 수동/자동 복권을 다시 구매해서 돈이 0원이 될때까지 무한 루프를 돌리도록 바꾼다(돈이 떨어지기 전엔 탈출 불가)
잘부탁드립니다!

2023-11-07 15:03 UTC, konempty requested changes
크 정말 세세하게 신경 많이쓰신것 같아서 고생하셨습니다 👍 👍 
전체적으로 매직 리터럴이 좀 보이는것 같은데 상수화를 하면 좋을것 같아요!
조금만더 수정 부탁드립니다!

2023-11-07 15:03 UTC, konempty commented on .gitignore
> +.DS_Store
<img width="165" alt="스크린샷 2023-11-07 오후 11 44 40" src="https://github.com/BI-kotlin-in-action/YuChangHo-Project/assets/44064530/72f73a4a-6a1c-4fac-879c-7fafa962bb59">


파일끝에 개행이 없다면 깃헙에서도 경고를 띄워주고
파일끝 개행은 일부 시스템에서는 없으면 에러를 일으킵니다..!
아래 URL을 확인해서 적용해주세요!

https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

2023-11-07 15:03 UTC, konempty commented on .gitignore
> +.DS_Store
그리고 .idea 폴더도 깃 이그노어 처리 해주시면 좋을것 같아요!

2023-11-07 15:03 UTC, konempty commented on src/main/kotlin/controller/LottoProgram.kt
> +        systemView = SystemView()
LottoProgram 초기화 할때 초기화 된다면 선언과 동시에 초기화 해도 괜찮지 않을까요??

2023-11-07 15:03 UTC, konempty commented on src/main/kotlin/controller/LottoProgram.kt
> +    }
한개의 메소드가 너무 거대해진 느낌인데 비슷한 코드끼리 묶어서 별도의 메소드로 빼준다면 좋을것 같아요~!

2023-11-07 15:03 UTC, konempty commented on src/main/kotlin/domain/Lotto.kt
> +class Lotto {
도메인 객체는 data class를 쓰는게 좋습니다!

2023-11-07 15:03 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        val money = readLine()!!.toInt()
요건 View에서 처리해야할 역할일것 같아요

2023-11-07 15:03 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        val count = money / 1000
1000이라는 매직넘버를 상수화 한다면 좋을것 같아요

2023-11-07 15:03 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        this.totalCount = count
이렇게 쓴다면 count를 쓰지않고 바로 
this.totalCount = money / 1000
라고 했어도 괜찮지 않을까요?

2023-11-07 15:03 UTC, konempty commented on src/main/kotlin/domain/Lotto.kt
> +class Lotto {
요 클래스 하나가 로또 게임에 대한 모든 정보를 들고 있는것 같은데
좀더 세세한 도메인으로 나누는게 좋을것 같아요~!

2023-11-07 15:03 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        lotto.manualLottoCount = readLine()!!.toInt()
readLine()대신 readLn()을 쓰시면 null-assertion을 안쓸수 있습니다!

2023-11-07 15:03 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        autoLottoNum.sort()
보다보니까 sort에 대한 코드가 많이보이는데
IntArray대신 SortedSet<Int>를 쓴다면 좋을것 같아요!

2023-11-07 15:03 UTC, konempty commented on src/main/kotlin/view/SystemView.kt
> +                0 -> prize += i * 100000
등수별 금액을 enum으로 관리하면 좋을것 같아요!

2023-11-07 15:03 UTC, konempty commented on src/main/kotlin/controller/LottoProgram.kt
> +        for (i in 0 until lotto.autoLottoCount) {
i는 안쓰는 값인것 같은데 그럴경우 for문 대신 repeat문을 쓰는게 더 좋습니다~!

2023-11-07 15:03 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        }
요건 코멘트는 아니고 단순 제안인데
중복 없이 숫자를 뽑는 로직은 셔플링과 subList를 사용하는거예요!
ex)
1, 2, 3, 4, 5, 6의 숫자 배열에서 중복없이 3개를 뽑으려면
셔플링 후(2, 6, 3, 4, 5, 1)
앞에서 부터 3개 추출 (2, 6, 3)

2023-11-07 15:03 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +                if (nums[i] in winNum) {
저라면 아래처럼 한줄로 처리할것 같아요!
val count = nums.count{num -> num in winNum}
그리고 더 나아가서 set을쓰게되면 코틀린에서는 intersect라는 두개의 컬렉션 사이의 겹치는 원소들을 반환해주는 메소드가 있어서
val count = nums.intersect(winNum)
으로 줄일수도 있습니다~!

2023-11-07 15:05 UTC, konempty commented
그리고 모든 변경사항을 한개의 커밋에 넣는건 별로 좋은 선택지가 아니예요 
다음 커밋 부터는 커밋을 자주자주 하고 커밋메시지가 커밋 내용을 잘 설명할수 있도록 해주세요!

2023-11-08 12:43 UTC, uch0731 commented
수정했습니다! 더 고칠부분이나 부족한 부분있으시면 꼭 말씀해주세요!!
잘 부탁드립니다

2023-11-08 17:08 UTC, uch0731 commented
리뷰를 다시 받을때는 re-request review를 눌러야하는지 몰랐네요...ㅠ
다시 눌러야하는지 모르고 계속 기다리기만 했습니다 ㅋㅋ큐ㅠㅠ
다음부터는 꼭 눌러서 알람이 가도록 하겠습니다

2023-11-09 01:49 UTC, konempty requested changes
크 코드가 많이 깔끔해졌네요 ㅋㅋㅋ
조금만더 수정 부탁드려요!

2023-11-09 01:49 UTC, konempty commented on .idea/vcs.xml
> +</project>
.idea 폴더 내용들이 아직 남아 있네요 ㅠㅠ
깃이그노어 처리하고 이미 올라간 파일들을 지워주는 작업까지 해야 하는데 아래 링크를 참고해주세요
https://devjeonblog.oopy.io/3d13207f-b830-4bbc-9d35-bd6dbfc824f0

2023-11-09 01:49 UTC, konempty commented on src/main/kotlin/controller/LottoProgram.kt
> +import java.util.*
@[konempty](https://github.com/konempty) konempty [2 days ago](https://github.com/BI-kotlin-in-action/JoSeungBin/pull/3#discussion_r1383463515)
헉 와일드 카드 임포트는 지양하는게 좋습니다
https://blog.leocat.kr/notes/2020/12/14/intellij-avoid-wildcard-imports-in-kotlin-with-intellij
요 블로그 참고해서 설정해주세요!

2023-11-09 01:49 UTC, konempty commented on src/main/kotlin/controller/LottoProgram.kt
> +        systemView.showFinishAutoLottoMessage()
사실 요정도 메소드도 긴편에 속해요 ㅋㅋㅋ...
보통 10라인 정도로 한개의 메소드를 만드는게 예쁘다고 이야기 많이하거든요
하지만 아직 초보자시니까 요정도 길이 메소드는 괜찮을것 같네요!

2023-11-09 01:49 UTC, konempty commented on src/main/kotlin/controller/LottoProgram.kt
> +            run()
구조를 보니까 리플레이를 몇만번쯤 하면 스택오버플로우로 프로그램이 터질것 같네요 ㅋㅋㅋ..
run -> reply -> run -> reply ~

2023-11-09 01:49 UTC, konempty commented on src/main/kotlin/domain/Lotto.kt
> +import java.util.*
요기도 와일드 카드가..!

2023-11-09 01:49 UTC, konempty commented on src/main/kotlin/domain/Lotto.kt
> +data class Lotto(var winNum: SortedSet<Int>)
SortedSet이 가변 컬렉션이기때문에 val로 선언하셔도 좋을것 같아요!

2023-11-09 01:49 UTC, konempty commented on src/main/kotlin/domain/User.kt
> +data class User(var manualLottoCount: Int, var autoLottoCount: Int, val lottoNum: MutableList<SortedSet<Int>>)
lottoNum은 의도로 봤을때 MutableList\<Lotto>가 더 어울리지 않을까요??

2023-11-09 01:49 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        val manualLottoNum = readLine()!!.split(" ").map { it.toInt() }.toSortedSet()
이렇게 하면 사용자가 중복된 숫자를 입력했을때 숫자가 6개 미만이 될수도 있지 않을까요??
아니면 6개 이상 입력해도 validation이 안될것 같구요 ㅠㅠ

2023-11-09 01:49 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        val manualLottoNum = readLine()!!.split(" ").map { it.toInt() }.toSortedSet()
그리고 리스트를 로또에 넣기위해 toSortedSet으로 변경하고 있는데
Lotto의 부 생성자로 리스트를 받아주고 내부에서 toSortedSet로 변경해서 사용하도록 하면 좋을것 같아요!

2023-11-09 01:49 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        val numbers = (LOTTO_START_NUM..LOTTO_END_NUM).toList()
요렇게 시작에서 부터 끝까지 나타내는 리스트는 프로그램 전역적으로 유니크 해도 좋을것 같은데
static하게 정의하면 어떨까요??

2023-11-09 01:49 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        shuffle(numbers)
numbers.shuffled() 혹은 numbers.shuffe() 라는 메소드가 이미 있으니까 그걸 사용하시면 됩니다~!
단, 요 두개의 용도가 조금 달라서 찾아보시고 필요에 따라 사용하시면 좋을것 같습니다~!

2023-11-09 01:49 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        }
저라면 
println(user.lottoNum.joinToString("\n"))
로 for문 쓰지않고 한줄로 처리할것 같아요!

2023-11-09 01:49 UTC, konempty commented on src/main/kotlin/domain/LottoResult.kt
> +data class LottoResult(var prize: Int, val rank: IntArray)
Rank가 Int배열이라 뭘 위한 변수일지 감이 잘 안오는것 같아요
`등수별 개수`라는 의도를 잘 나타내려면 Map<PrizeByRank, Int>가 좋을것 같아요!

2023-11-09 01:49 UTC, konempty commented on src/main/kotlin/view/SystemView.kt
> +    enum class prizeByRank(val rank: Int, val prize: Int) {
클래스 명이 소문자로 시작하면 좋지 않아요 ㅋㅋㅋ

2023-11-09 01:49 UTC, konempty commented on src/main/kotlin/view/SystemView.kt
> +        val money = readLine()!!.toInt()
readLine 대신에 readLn을 쓰면 null-assertion을 땔수 있습니다!

2023-11-09 06:50 UTC, uch0731 commented on src/main/kotlin/controller/LottoProgram.kt
> +        systemView.showFinishAutoLottoMessage()
그렇군요...더 줄여보겠습니다

2023-11-09 06:52 UTC, uch0731 commented on src/main/kotlin/domain/User.kt
> +data class User(var manualLottoCount: Int, var autoLottoCount: Int, val lottoNum: MutableList<SortedSet<Int>>)
그렇네요! 수정하겠습니다

2023-11-09 06:52 UTC, uch0731 commented on src/main/kotlin/service/LottoService.kt
> +        val manualLottoNum = readLine()!!.split(" ").map { it.toInt() }.toSortedSet()
넵 알겠습니다! validation은 아직 구현을 못했어요 ㅠㅠ

2023-11-09 09:24 UTC, uch0731 commented on src/main/kotlin/controller/LottoProgram.kt
> +            run()
그러면 어떤 방식으로 하는게 더 좋을까요? 고민해봤는데 결국 스태오버플로우가 일어날 것 같아서 여쭤봅니다!

2023-11-09 09:46 UTC, uch0731 commented on src/main/kotlin/service/LottoService.kt
> +        val numbers = (LOTTO_START_NUM..LOTTO_END_NUM).toList()
그렇게 하는게 훨씬 좋은 것 같아요

2023-11-09 11:42 UTC, konempty requested changes
크 거의 다온것 같아요!!
진짜 조금만더 수정부탁드릴게요!

2023-11-09 11:42 UTC, konempty commented on src/main/kotlin/controller/LottoProgram.kt
> +            run()
간단하게 무한 루프만 돌려도 괜찮지 않을까요 ㅋㅋㅋ

2023-11-09 11:42 UTC, konempty commented on src/main/kotlin/domain/Lotto.kt
> +data class Lotto(val num: SortedSet<Int>) {
사실 제대로된 일급 컬렉션을 만드려면 컬렉션을 private로 숨기고 외부에서 직접 접근하는걸 차단 해야 해요..!

2023-11-09 11:42 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +                val prizeByRank = PrizeByRank.values().find { it.rank == LOTTO_SIZE - count + 1 }!!
요 코드를 아예 PrizeByRank의 static 메소드로 있으면 좋으것 같아요!

2023-11-09 11:42 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        val NUMBERS = (LOTTO_START_NUM..LOTTO_END_NUM).toList()
const를 붙힐수 없다면 \@JvmStatic이라는 어노테이션을 붙혀줘야 자바의 static에 대응되는 코드입니다!

2023-11-09 11:42 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        user.manualLottoCount = readln().toInt()
사용자가 음수나, 구매가능한 숫자보다 큰 수를 입력했을때 심지어 숫자가 아닌 이상한 값을 입력했을때의
validation이 있으면 좋을것 같아요!

2023-11-09 11:42 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        val manualLottoNum = Lotto(readln().split(" ").map { it.toInt() })
만약 사용자가 6개도 안되는 숫자를 입력하거나 6개를 넘는 숫자 배열을 입력하는 케이스 validation을 해야 할것 같아요!

2023-11-09 11:42 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        return shuffledNums.subList(0, LOTTO_SIZE)
subList보다는 take(LOTTO_SIZE) 라는 메소드를 쓰는게 좋습니다~!

2023-11-09 11:42 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        println(user.lottoNum.joinToString("\n"))
화면 출력은 View의 역할일것 같아요!

2023-11-14 04:58 UTC, uch0731 commented
수정했습니다! 부족한 점 혹은 더 고칠 점 있으시면 말씀해주세요!
잘부탁드립니다 ㅎㅎ

2023-11-14 11:40 UTC, konempty requested changes
너무 고생많이 하셨는데
진짜 쪼금만더 수정 부탁드릴게요..! ㅎㅎㅎ

2023-11-14 11:40 UTC, konempty commented on src/main/kotlin/domain/User.kt
> +data class User(var manualLottoCount: Int, var autoLottoCount: Int, val lottoNum: MutableList<Lotto>)
lottoNum까지 외부에서 주입받을 필요가 있을까요??
디폴트값을 주거나 생성자로 주입받지 않도록 해도 될것 같아요!
ex)
```kotlin
data class User(var manualLottoCount: Int, var autoLottoCount: Int, val lottoNum: MutableList<Lotto> = mutableListOf())

// 혹은 

data class User(var manualLottoCount: Int, var autoLottoCount: Int){
    val lottoNum: MutableList<Lotto> = mutableListOf()
}
```

그리고 lottoNum이라는 프로퍼티를 직접 노출해서 가변성을 노출하는것보다
addLotto라는 private메소드를 통해서 제한적으로 노출하도록 하면 좋을것 같아요!
지금 코드에서는 lottoNum를 외부에서 마음대로 수정할수 있을것 같아서 아쉬워 보이네요 ㅋㅋㅋ

2023-11-14 11:40 UTC, konempty commented on src/main/kotlin/domain/LottoResult.kt
> +data class LottoResult(var prize: Int, val rank: HashMap<PrizeByRank, Int>)
여기도 rank를 굳이 외부에서 주입 받아야 하는지 잘 모르겠네요

2023-11-14 11:40 UTC, konempty commented on src/main/kotlin/domain/Lotto.kt
> +        return num
앗 ㅋㅋㅋ.. 요렇게 하면 num을 private로 숨긴 의미가 퇴색될것 같아요

2023-11-14 11:40 UTC, konempty commented on src/main/kotlin/domain/PrizeByRank.kt
> +            var count = userLotto.getLottoNum().intersect(winNum).size
아핫 ㅋㅋ... 맞춘 count까지 PrizeByRank가 할일은 아닌것 같아요
fun getRank(count:Int): PrizeByRank 
요런 느낌으로 해주시면 좋을것 같아요!

2023-11-14 11:40 UTC, konempty commented on src/main/kotlin/domain/PrizeByRank.kt
> +            }
```kotlin
return values().find { it.rank == LottoService.LOTTO_SIZE - count + 1 } ?: LOSE
```
요렇게 하면 if문을 없앨수 있습니다~!

2023-11-14 11:40 UTC, konempty commented on src/main/kotlin/service/Validator.kt
> +class Validator {
크 validator라는 역할까지 분리하다니 너무 좋습니다 👍 👍 💯

2023-11-14 11:40 UTC, konempty commented on src/main/kotlin/service/Validator.kt
> +        if (input.size != size) {
size를 파라메터로 받지 않고 LottoService.LOTTO_SIZE 를 쓴다면 어떨까요??

2023-11-14 11:40 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        val NUMBERS = (LOTTO_START_NUM..LOTTO_END_NUM).toList()
그러고보니 NUMBERS를 List로 바꿔주는 이유가 있을까요?? IntRange여도 괜찮을것 같아서요

2023-11-14 11:40 UTC, konempty commented on src/main/kotlin/service/Validator.kt
> +        if (input < startNum || input > endNum) {
만약 LottoService.Numbers가 IntRange라면 여기는
`input !in LottoService.Numbers`
요렇게 할수 있을것 같아요!

2023-11-14 11:40 UTC, konempty commented on src/main/kotlin/view/SystemView.kt
> +    var canBuy: Int = 0
요걸 저장하고 있는건 뷰의 역할이 아닐것 같아요
뷰는 순수하게 입력 받고 출력하는 역할만 해야지 정보를 저장하는 역할은 어울리지 않거든요!

2023-11-14 11:40 UTC, konempty commented on src/main/kotlin/domain/User.kt
> +data class User(var manualLottoCount: Int, var autoLottoCount: Int, val lottoNum: MutableList<Lotto>)
지금 보니 프로퍼티 3개가 생성자에서 다 외부로 부터 값을 주입받을 필요가 없어보이네요 ㅋㅋㅋ

2023-11-15 03:07 UTC, uch0731 commented on src/main/kotlin/domain/User.kt
> +data class User(var manualLottoCount: Int, var autoLottoCount: Int, val lottoNum: MutableList<Lotto>)
private method를 사용하면 외부에서 그 메소드를 사용할 수 없는거 아닌가요?!

2023-11-15 03:14 UTC, uch0731 commented on src/main/kotlin/domain/Lotto.kt
> +        return num
그러면 private val 인 num을 혹시 외부에서 사용할 수 있는 다른 방법이 있을까요?!

2023-11-15 03:56 UTC, uch0731 commented on src/main/kotlin/service/Validator.kt
> +        if (input.size != size) {
그게 더 좋을 것 같아요!

2023-11-15 03:56 UTC, uch0731 commented on src/main/kotlin/domain/PrizeByRank.kt
> +            }
감사합니다!

2023-11-15 03:56 UTC, uch0731 commented on src/main/kotlin/domain/PrizeByRank.kt
> +            var count = userLotto.getLottoNum().intersect(winNum).size
넵 알겠습니다

2023-11-15 03:56 UTC, uch0731 commented on src/main/kotlin/domain/LottoResult.kt
> +data class LottoResult(var prize: Int, val rank: HashMap<PrizeByRank, Int>)
그러게여 수정했습니다!

2023-11-15 03:57 UTC, uch0731 commented on src/main/kotlin/service/Validator.kt
> +        if (input < startNum || input > endNum) {
IntRange가 더 좋은것 같아요!
rangeCheck부분도 수정했습니다!

2023-11-15 03:58 UTC, uch0731 commented on src/main/kotlin/view/SystemView.kt
> +    var canBuy: Int = 0
데이터클래스로 옮겼습니다. 감사합니다!

2023-11-15 04:17 UTC, uch0731 commented
코멘트 듣고 최대한 고쳐봤는데 private 변수를 어떻게 외부에서 사용해야 할 지 모르겠네요.. 그 private변수에 관한 메소드도 
어떻게 선언해야할지 모르겠어요! 이 부분만 조금 더 도움을 주시면 감사하겠습니다. 다른 부분에서도 부족한 점이나 고칠점 
있으면 말씀해주세요!

2023-11-15 11:07 UTC, konempty commented on src/main/kotlin/domain/Lotto.kt
> +        return num
가변성 노출 제한을 위해 Set<Int>라고 선언했어야 한다고 생각해요

2023-11-15 11:07 UTC, konempty commented on src/main/kotlin/domain/User.kt
> +data class User(var canBuy: Int = 0, var manualLottoCount: Int = 0, var autoLottoCount: Int = 0, private val lottoNum: MutableList<Lotto> = mutableListOf<Lotto>()) {
lottoNum이 아니라 로또 리스트를 잘 나타내는 이름이면 좋을것 같아요!

2023-11-15 11:07 UTC, konempty commented on src/main/kotlin/domain/User.kt
> +    fun getLottoNum(): MutableList<Lotto> {
여기도 가변성 노출을 최소화했으면 좋을것 같아요

2023-11-15 11:07 UTC, konempty commented on src/main/kotlin/domain/User.kt
> +data class User(var manualLottoCount: Int, var autoLottoCount: Int, val lottoNum: MutableList<Lotto>)
아 ㅋㅋㅋ 그렇네요 public메소드를 노출하라고 하고 싶었는데 반대로 이야기 햇네요

2023-11-15 11:16 UTC, konempty requested changes
진짜 조금만더 수정 부탁드릴게요!

2023-11-15 11:16 UTC, konempty commented on src/main/kotlin/service/LottoService.kt
> +        val money = moneyCheck(readln())
사용자 인풋을 받는건 뷰의 역할이예요!
그리고 LottoService와 LottoProgram가 컨트롤러의 역할을 나눠가진것 같은데
혹시 어떤 기준으로 나눠가진건지 알수 있을까요??

2023-11-15 12:08 UTC, uch0731 commented
그러면 인풋 받는 모든 부분을 view로 옮겨야 할까요? 
제 머릿속에서는 컨트롤러의 역할을 로또 프로그램만하게하고 로또 서비스는 서비스적 기능만 하도록 설계했는데...
어느 로또서비스의 어느부분을 컨트롤러로 바꿔야할가요

2023-11-15 13:08 UTC, konempty commented
서비스적 역할이라는게 어떤 역할인지 설명해주실수 있나요??

2023-11-15 13:13 UTC, konempty commented
요 프로젝트에서 나눌만한 3가지 패키지을 알려드릴게요!

도메인 : 단순히 정보를 가지고 패키지 간의 정보 전달을 위해 사용되는 클래스 모음
뷰 : IO에 관련된 모든 로직을 수행하는 클래스 모음
컨트롤러 : 뷰와 도메인을 받아들여 프로그램의 전체과정을 컨트롤하는 역할

2023-11-15 13:47 UTC, uch0731 commented
저는  로또 프로그램의 기능을 서비스적 역할이라고 생각했어요. 
그리고 컨트롤러에서는 로또 서비스의 기능과, 뷰를 이용해서 로또 프로그램을 진행시키는 역할을 원했는데 지금 보니
컨트롤러가 좀 더 많은 역할을 수행하고 있는 것 같기도 ㅎ ㅏ네요...

2023-11-15 17:37 UTC, uch0731 commented
우선 입력받는 기능을 전부 view 로 옮겼는데 view에서 입력받은 걸 리턴하는 기능도 해야하는게 맞는건지 궁금해요!
그리고 컨트롤러의 역할을 service로 주려고 해봤는데 뭘 줘야할지 도저히 감이 안잡히네요...

2023-11-16 00:46 UTC, konempty commented
> 우선 입력받는 기능을 전부 view 로 옮겼는데 view에서 입력받은 걸 리턴하는 기능도 해야하는게 맞는건지 궁금해요!

정확하게 제가 의도하는 바예요 ㅋㅋㅋ
뷰는 입력 받은걸 validation하고 외부에 전달해주면 그 정보를 누군가 받아서 초기화 하는데 사용하면 됩니다~!

2023-11-16 00:56 UTC, konempty requested changes
아하 ㅠㅠ 쪼금 아쉬운게 보이는것 같은데
쪼금만더 수정부탁드릴게요

2023-11-16 00:56 UTC, konempty commented on src/main/kotlin/domain/LottoResult.kt
> +data class LottoResult(var prize: Int = 0, val rank: HashMap<PrizeByRank, Int> = HashMap<PrizeByRank, Int>())
아하 ㅋㅋㅋ.. 이전에 리뷰 드린 내용 여기도 적용해주시는걸 바랬는데
rank도 가변성 노출을 제한할수 있을것 같아요!

2023-11-16 00:56 UTC, konempty commented on src/main/kotlin/domain/Lotto.kt
> +data class Lotto(private val num: SortedSet<Int>) {
요것도 외부에서 주입받을 필요는 없어보이는데 디폴트 값을 주는건 어떨까요?

2023-11-16 00:56 UTC, konempty commented on src/main/kotlin/domain/PrizeByRank.kt
> +            return values().find { it.rank == LottoService.LOTTO_SIZE - count + 1 } ?: LOSE
뭔가 계산 로직이 복잡해 보이는데
각 등수 별 맞아야하는 번호의 개수를 지정해둔다면 식이 간단해 지지 않을까요??
FIRST(1, 6, 100000),
SECOND(2, 5, 5000),
... 중략

values().find { it.맞아야하는_개수 ==  count  } ?: LOSE

2023-11-16 00:56 UTC, konempty commented on src/main/kotlin/domain/User.kt
> +data class User(var canBuy: Int = 0, var manualLottoCount: Int = 0, var autoLottoCount: Int = 0, private val lottoNumList: MutableList<Lotto> = mutableListOf<Lotto>()) {
이렇게 전부다 디폴트 값이 있는게 좀 이상한것 같아요 ㅠㅠ
객체 생성과 값 초기화 시점이 분리되어있어서 이런 현상이 있는것 같은데
객체 생성할때 각 프로퍼티의 값을 한번에 초기화 할수 있도록 하면 어떨까요??
그리고 컬렉션 타입인 lottoNumList는 생성자에서 선언하는게 아니라 일반 프로퍼티로 선언해도 좋을것 같아요

as-is:
val user = User()
user.canBuy = 10
user.manualLottoCount = 3
... 중략

to-be:
val user = User(10, 3 ...)

2023-11-16 04:14 UTC, uch0731 commented
마지막 코멘트 빼고 다 수정했습니다!
마지막 코멘트에서 유저클래스 프로퍼티의 값을 한번에 초기화 할 수 있도록 하면 어떠냐고 하셨는데
lateinit을 써서 한번에 초기화 할 수 있을 것 같긴한데 각자의 값이 구해지는 위치가 다르다보니 조금 애매하네요

2023-11-16 04:32 UTC, konempty approved these changes
크 정말 고생이 많으셨어요!
아직 쪼금더 리뷰할만한 내용이 있는것 같지만 그래도 요정도면 
초보자 치곤 너무 과분할정도로 잘해주신것 같아요 ㅋㅋㅋ

뷰에 있는 메소드 들만 한개의 역할을 수행하도록만 바꿔주시면 좋을것 같습니다~!

2023-11-16 04:32 UTC, konempty commented on src/main/kotlin/controller/LottoProgram.kt
> +        val money = systemView.showStartMessage(user.canBuy)
메소드 이름만 본다면 showStartMessage라는 이름은 순수하게 화면 출력만 담당할거라고 기대되는데
실제로는 값 입력까지 담당하나보네요
한개의 메소드가 2개의 역할을 수행하는것 같아서 두개의 역할을 쪼갰으면 좋을것 같구요
그게 정말 어렵다면 이름을 메소드의 역할에 맞게 직관적으로 지어주세요..!
다른 뷰 메소드들도 동일하구요!

2023-11-16 04:43 UTC, uch0731 commented
뷰에서 메시지 출력부분과 사용자의 입력을 받아오는 부분을 나눴습니다!
머지하기전에 
user객체 lateinit으로 나중에 한번에 초기화하기를 원하셨던게 맞는지 여쭤보고 싶습니다!
처음부터 초기화를 한번에 할 방법이 떠오르질 않아서 질문드립니당

2023-11-16 04:47 UTC, konempty commented on src/main/kotlin/controller/LottoProgram.kt
> +            canBuy = lottoService.canBuyMax(money) }
코드 포멧팅이 이상하네요 ;;

2023-11-16 04:51 UTC, konempty commented on src/main/kotlin/view/SystemView.kt
> +        if (canBuy == 0) {
으흠... 제가 생각한거랑 쪼금 다르게 생겼었군요
인풋을 유도하기위한 화면 출력문구는 괜찮은데
저는 메소드명만 보고 판단하다보니 화면에 출력하는 코드 여러줄 + 사용자 입력 받는 코드 1줄 요렇게 생겼을것이라고
유추했습니닷..!

차라리 이경우 요 변경사항을 롤백하고 메소드 명을 show라는 행위보다는 `변수값을 입력받는다`라는 행위에 더 집중하도록
이름을 다시지어주시는게 좋은 코드일것 같아요!

2023-11-16 04:52 UTC, konempty commented
유저 정보를 입력받는건 코드 구조상 지금 하신 정도면 어쩔수 없이 타협하고 넘어가야 할것 같아요 ㅋㅋㅋ큐ㅠㅠ

2023-11-16 05:19 UTC, uch0731 commented
넵 다 수정했습니다! 피드백 끝까지 해주셔서 감사합니다! 머지하겠습니당

2023-11-16 05:19 UTC, merged